theme = "yellowed"

# Editor
[editor]
line-number = "relative"
mouse = false
bufferline = "multiple"
rulers = [80]
true-color = true

[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'`' = '`'

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.lsp]
# Show LSP messages in the status line
display-messages = true

[editor.statusline]
left = ["mode", "spinner", "file-name"]
right = ["read-only-indicator", "diagnostics", "position"]

[editor.soft-wrap]
enable = true

[editor.auto-save]
focus-lost = true

[editor.file-picker]
git-ignore = true
ignore = true

# Keys
[keys.normal]
X = "extend_line_above"

[keys.normal.space]
z = ":pipe-to hepl.sh send"
Z.p = ":run-shell-command hepl.sh spawn python3"

[keys.insert]
C-h = "move_char_left"
C-l = "move_char_right"
# A-a = "goto_line_end_newline"
# A-i = "goto_line_start"
# A-j = "move_visual_line_down"
# A-k = "move_visual_line_up"
j = { k = "normal_mode" }


[editor.gutters]
layout = ["diff", "diagnostics", "spacer", "line-numbers", "spacer"]

[editor.gutters.line-numbers]
min-width = 1

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
nnbsp = "␣"
tab = "→"
newline = "⏎"
tabpad = "·" # Tabs will look like "→···" (depending on tab width)
